# Generated by Django 5.2.12 on 2026-03-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("concert", "Concert"),
                            ("sports", "Sports"),
                            ("festival", "Festival"),
                            ("theatre", "Theatre"),
                        ],
                        max_length=200,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=200)),
                ("venue", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_seats", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
